{% set name = "multitasking" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multitasking-{{ version }}.tar.gz
  sha256: b59d99f709d2e17d60ccaa2be09771b6e9ed9391c63f083c0701e724f624d2e0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - multitasking
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ranaroussi/multitasking
  summary: Non-blocking Python methods using decorators
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kc
